package om.apps.sms.model.entities;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 14 16:37:26 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhceHeSmsHeadersEOImpl extends SMSEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        HeaderId,
        SiteId,
        CreationDate,
        CreatedBy,
        LastUpdatedDate,
        LastUpdatedBy,
        CustomerAccountNumber,
        PoNumber,
        ListHeaderId,
        Attribute1,
        Attribute2,
        Attribute3,
        Attribute4,
        Attribute5,
        Attribute6,
        Attribute7,
        Attribute8,
        Attribute9,
        Attribute10,
        Attribute11,
        Attribute12,
        Attribute13,
        Attribute14,
        Attribute15,
        Attribute16,
        Attribute17,
        Attribute18,
        Attribute19,
        Attribute20,
        Attribute21,
        Attribute22,
        Attribute23,
        Attribute24,
        Attribute25,
        Attribute26,
        Attribute27,
        Attribute28,
        Attribute29,
        Attribute30,
        Type,
        OrgId,
        InvOrgId,
        ShipToSiteUseId,
        BillToSiteUseId,
        SerialVersionId,
        XxhceHeSmsLinesEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CUSTOMERACCOUNTNUMBER = AttributesEnum.CustomerAccountNumber.index();
    public static final int PONUMBER = AttributesEnum.PoNumber.index();
    public static final int LISTHEADERID = AttributesEnum.ListHeaderId.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int INVORGID = AttributesEnum.InvOrgId.index();
    public static final int SHIPTOSITEUSEID = AttributesEnum.ShipToSiteUseId.index();
    public static final int BILLTOSITEUSEID = AttributesEnum.BillToSiteUseId.index();
    public static final int SERIALVERSIONID = AttributesEnum.SerialVersionId.index();
    public static final int XXHCEHESMSLINESEO = AttributesEnum.XxhceHeSmsLinesEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhceHeSmsHeadersEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("om.apps.sms.model.entities.XxhceHeSmsHeadersEO");
    }


    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the value of HeaderId
     */
    public BigDecimal getHeaderId() {
        return (BigDecimal) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(BigDecimal value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for SiteId, using the alias name SiteId.
     * @return the value of SiteId
     */
    public BigDecimal getSiteId() {
        return (BigDecimal) getAttributeInternal(SITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SiteId.
     * @param value value to set the SiteId
     */
    public void setSiteId(BigDecimal value) {
        setAttributeInternal(SITEID, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for CustomerAccountNumber, using the alias name CustomerAccountNumber.
     * @return the value of CustomerAccountNumber
     */
    public BigDecimal getCustomerAccountNumber() {
        return (BigDecimal) getAttributeInternal(CUSTOMERACCOUNTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerAccountNumber.
     * @param value value to set the CustomerAccountNumber
     */
    public void setCustomerAccountNumber(BigDecimal value) {
        setAttributeInternal(CUSTOMERACCOUNTNUMBER, value);
    }

    /**
     * Gets the attribute value for PoNumber, using the alias name PoNumber.
     * @return the value of PoNumber
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoNumber.
     * @param value value to set the PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**
     * Gets the attribute value for ListHeaderId, using the alias name ListHeaderId.
     * @return the value of ListHeaderId
     */
    public BigDecimal getListHeaderId() {
        return (BigDecimal) getAttributeInternal(LISTHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ListHeaderId.
     * @param value value to set the ListHeaderId
     */
    public void setListHeaderId(BigDecimal value) {
        setAttributeInternal(LISTHEADERID, value);
    }


    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the value of Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the value of Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the value of Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the value of Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the value of Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the value of Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the value of Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the value of Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the value of Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the value of Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the value of Attribute11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the value of Attribute12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the value of Attribute13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the value of Attribute14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the value of Attribute15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the value of Attribute16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the value of Attribute17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the value of Attribute18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the value of Attribute19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the value of Attribute20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for Attribute21, using the alias name Attribute21.
     * @return the value of Attribute21
     */
    public BigDecimal getAttribute21() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute21.
     * @param value value to set the Attribute21
     */
    public void setAttribute21(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for Attribute22, using the alias name Attribute22.
     * @return the value of Attribute22
     */
    public BigDecimal getAttribute22() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute22.
     * @param value value to set the Attribute22
     */
    public void setAttribute22(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for Attribute23, using the alias name Attribute23.
     * @return the value of Attribute23
     */
    public BigDecimal getAttribute23() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute23.
     * @param value value to set the Attribute23
     */
    public void setAttribute23(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for Attribute24, using the alias name Attribute24.
     * @return the value of Attribute24
     */
    public BigDecimal getAttribute24() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute24.
     * @param value value to set the Attribute24
     */
    public void setAttribute24(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for Attribute25, using the alias name Attribute25.
     * @return the value of Attribute25
     */
    public BigDecimal getAttribute25() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute25.
     * @param value value to set the Attribute25
     */
    public void setAttribute25(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for Attribute26, using the alias name Attribute26.
     * @return the value of Attribute26
     */
    public Timestamp getAttribute26() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute26.
     * @param value value to set the Attribute26
     */
    public void setAttribute26(Timestamp value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for Attribute27, using the alias name Attribute27.
     * @return the value of Attribute27
     */
    public Timestamp getAttribute27() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute27.
     * @param value value to set the Attribute27
     */
    public void setAttribute27(Timestamp value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for Attribute28, using the alias name Attribute28.
     * @return the value of Attribute28
     */
    public Timestamp getAttribute28() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute28.
     * @param value value to set the Attribute28
     */
    public void setAttribute28(Timestamp value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for Attribute29, using the alias name Attribute29.
     * @return the value of Attribute29
     */
    public Timestamp getAttribute29() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute29.
     * @param value value to set the Attribute29
     */
    public void setAttribute29(Timestamp value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for Attribute30, using the alias name Attribute30.
     * @return the value of Attribute30
     */
    public Timestamp getAttribute30() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute30.
     * @param value value to set the Attribute30
     */
    public void setAttribute30(Timestamp value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for Type, using the alias name Type.
     * @return the value of Type
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Type.
     * @param value value to set the Type
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the value of OrgId
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for InvOrgId, using the alias name InvOrgId.
     * @return the value of InvOrgId
     */
    public BigDecimal getInvOrgId() {
        return (BigDecimal) getAttributeInternal(INVORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvOrgId.
     * @param value value to set the InvOrgId
     */
    public void setInvOrgId(BigDecimal value) {
        setAttributeInternal(INVORGID, value);
    }

    /**
     * Gets the attribute value for ShipToSiteUseId, using the alias name ShipToSiteUseId.
     * @return the value of ShipToSiteUseId
     */
    public BigDecimal getShipToSiteUseId() {
        return (BigDecimal) getAttributeInternal(SHIPTOSITEUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToSiteUseId.
     * @param value value to set the ShipToSiteUseId
     */
    public void setShipToSiteUseId(BigDecimal value) {
        setAttributeInternal(SHIPTOSITEUSEID, value);
    }

    /**
     * Gets the attribute value for BillToSiteUseId, using the alias name BillToSiteUseId.
     * @return the value of BillToSiteUseId
     */
    public BigDecimal getBillToSiteUseId() {
        return (BigDecimal) getAttributeInternal(BILLTOSITEUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillToSiteUseId.
     * @param value value to set the BillToSiteUseId
     */
    public void setBillToSiteUseId(BigDecimal value) {
        setAttributeInternal(BILLTOSITEUSEID, value);
    }

    /**
     * Gets the attribute value for SerialVersionId, using the alias name SerialVersionId.
     * @return the value of SerialVersionId
     */
    public BigDecimal getSerialVersionId() {
        return (BigDecimal) getAttributeInternal(SERIALVERSIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SerialVersionId.
     * @param value value to set the SerialVersionId
     */
    public void setSerialVersionId(BigDecimal value) {
        setAttributeInternal(SERIALVERSIONID, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxhceHeSmsLinesEO() {
        return (RowIterator) getAttributeInternal(XXHCEHESMSLINESEO);
    }

    /**
     * @param headerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal headerId) {
        return new Key(new Object[] { headerId });
    }


}

