package om.apps.sms.model.entities;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 29 21:03:08 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhceHeSmsSiteTypeEOImpl extends SMSEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TypeId,
        TypeName,
        SiteId,
        Status,
        CreationDate,
        CreatedBy,
        LastUpdatedBy,
        LastUpdatedDate,
        SerialVersionId,
        BatchSourceId,
        CreditMemoTypeId,
        CustTrxTypeId,
        Ou,
        XxhceHeSmsSiteMtncEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TYPEID = AttributesEnum.TypeId.index();
    public static final int TYPENAME = AttributesEnum.TypeName.index();
    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SERIALVERSIONID = AttributesEnum.SerialVersionId.index();
    public static final int BATCHSOURCEID = AttributesEnum.BatchSourceId.index();
    public static final int CREDITMEMOTYPEID = AttributesEnum.CreditMemoTypeId.index();
    public static final int CUSTTRXTYPEID = AttributesEnum.CustTrxTypeId.index();
    public static final int OU = AttributesEnum.Ou.index();
    public static final int XXHCEHESMSSITEMTNCEO = AttributesEnum.XxhceHeSmsSiteMtncEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhceHeSmsSiteTypeEOImpl() {
    }

    /**
     * Gets the attribute value for TypeId, using the alias name TypeId.
     * @return the value of TypeId
     */
    public BigDecimal getTypeId() {
        return (BigDecimal) getAttributeInternal(TYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypeId.
     * @param value value to set the TypeId
     */
    public void setTypeId(BigDecimal value) {
        setAttributeInternal(TYPEID, value);
    }

    /**
     * Gets the attribute value for TypeName, using the alias name TypeName.
     * @return the value of TypeName
     */
    public String getTypeName() {
        return (String) getAttributeInternal(TYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypeName.
     * @param value value to set the TypeName
     */
    public void setTypeName(String value) {
        setAttributeInternal(TYPENAME, value);
    }

    /**
     * Gets the attribute value for SiteId, using the alias name SiteId.
     * @return the value of SiteId
     */
    public BigDecimal getSiteId() {
        return (BigDecimal) getAttributeInternal(SITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SiteId.
     * @param value value to set the SiteId
     */
    public void setSiteId(BigDecimal value) {
        setAttributeInternal(SITEID, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for SerialVersionId, using the alias name SerialVersionId.
     * @return the value of SerialVersionId
     */
    public BigDecimal getSerialVersionId() {
        return (BigDecimal) getAttributeInternal(SERIALVERSIONID);
    }

    /**
     * Gets the attribute value for BatchSourceId, using the alias name BatchSourceId.
     * @return the value of BatchSourceId
     */
    public Long getBatchSourceId() {
        return (Long) getAttributeInternal(BATCHSOURCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchSourceId.
     * @param value value to set the BatchSourceId
     */
    public void setBatchSourceId(Long value) {
        setAttributeInternal(BATCHSOURCEID, value);
    }

    /**
     * Gets the attribute value for CreditMemoTypeId, using the alias name CreditMemoTypeId.
     * @return the value of CreditMemoTypeId
     */
    public Long getCreditMemoTypeId() {
        return (Long) getAttributeInternal(CREDITMEMOTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditMemoTypeId.
     * @param value value to set the CreditMemoTypeId
     */
    public void setCreditMemoTypeId(Long value) {
        setAttributeInternal(CREDITMEMOTYPEID, value);
    }

    /**
     * Gets the attribute value for CustTrxTypeId, using the alias name CustTrxTypeId.
     * @return the value of CustTrxTypeId
     */
    public Long getCustTrxTypeId() {
        return (Long) getAttributeInternal(CUSTTRXTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustTrxTypeId.
     * @param value value to set the CustTrxTypeId
     */
    public void setCustTrxTypeId(Long value) {
        setAttributeInternal(CUSTTRXTYPEID, value);
    }

    /**
     * Gets the attribute value for Ou, using the alias name Ou.
     * @return the value of Ou
     */
    public String getOu() {
        return (String) getAttributeInternal(OU);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ou.
     * @param value value to set the Ou
     */
    public void setOu(String value) {
        setAttributeInternal(OU, value);
    }

    /**
     * @return the associated entity XxhceHeSmsSiteMtncEOImpl.
     */
    public XxhceHeSmsSiteMtncEOImpl getXxhceHeSmsSiteMtncEO() {
        return (XxhceHeSmsSiteMtncEOImpl) getAttributeInternal(XXHCEHESMSSITEMTNCEO);
    }

    /**
     * Sets <code>value</code> as the associated entity XxhceHeSmsSiteMtncEOImpl.
     */
    public void setXxhceHeSmsSiteMtncEO(XxhceHeSmsSiteMtncEOImpl value) {
        setAttributeInternal(XXHCEHESMSSITEMTNCEO, value);
    }

    /**
     * @param typeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal typeId) {
        return new Key(new Object[] { typeId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("om.apps.sms.model.entities.XxhceHeSmsSiteTypeEO");
    }
}

