package om.apps.sms.model.entities;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 23 16:07:56 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhceHeSmsSiteMtncEOImpl extends SMSEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        SiteId,
        OrganizationId,
        OrganizationCode,
        Status,
        CreationDate,
        CreatedBy,
        LastUpdatedDate,
        LastUpdatedBy,
        Id,
        SerialVersionId,
        XxhceHeSmsSiteTypeEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();
    public static final int ORGANIZATIONCODE = AttributesEnum.OrganizationCode.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int SERIALVERSIONID = AttributesEnum.SerialVersionId.index();
    public static final int XXHCEHESMSSITETYPEEO = AttributesEnum.XxhceHeSmsSiteTypeEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhceHeSmsSiteMtncEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("om.apps.sms.model.entities.XxhceHeSmsSiteMtncEO");
    }


    /**
     * Gets the attribute value for SiteId, using the alias name SiteId.
     * @return the value of SiteId
     */
    public oracle.jbo.domain.Number getSiteId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(SITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SiteId.
     * @param value value to set the SiteId
     */
    public void setSiteId(oracle.jbo.domain.Number value) {
        setAttributeInternal(SITEID, value);
    }

    /**
     * Gets the attribute value for OrganizationId, using the alias name OrganizationId.
     * @return the value of OrganizationId
     */
    public BigDecimal getOrganizationId() {
        return (BigDecimal) getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrganizationId.
     * @param value value to set the OrganizationId
     */
    public void setOrganizationId(BigDecimal value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * Gets the attribute value for OrganizationCode, using the alias name OrganizationCode.
     * @return the value of OrganizationCode
     */
    public String getOrganizationCode() {
        return (String) getAttributeInternal(ORGANIZATIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrganizationCode.
     * @param value value to set the OrganizationCode
     */
    public void setOrganizationCode(String value) {
        setAttributeInternal(ORGANIZATIONCODE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for SerialVersionId, using the alias name SerialVersionId.
     * @return the value of SerialVersionId
     */
    public BigDecimal getSerialVersionId() {
        return (BigDecimal) getAttributeInternal(SERIALVERSIONID);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxhceHeSmsSiteTypeEO() {
        return (RowIterator) getAttributeInternal(XXHCEHESMSSITETYPEEO);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[] { id });
    }


}

