package om.apps.sms.model.views.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 24 11:31:23 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SiteStatusLOVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SiteStatusLOVVOImpl() {
    }
}

