package om.apps.sms.model.modules.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 25 11:43:57 IST 2021
// ---------------------------------------------------------------------
public interface SMSAM extends ApplicationModule {
    void createAndSave();

    void initializeHdr();

    void addDetails();

    void deleteDetails();

    void clearHdrDtl();

    void saveValidData();

    oracle.jbo.domain.Number getSequenceNumber(String seq);

    String getInstanceName();

    boolean isEBSUser(String userName);

    void addSetup();

    void saveSetup();

    void addTypes();

    void deleteTypes();
}

