package om.apps.sms.model.views;

import java.math.BigDecimal;

import java.sql.Timestamp;

import om.apps.sms.model.entities.XxhceHeSmsSiteTypeEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 29 21:03:15 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhceHeSmsSiteTypeEOVORowImpl extends ViewRowImpl {
    public static final int ENTITY_XXHCEHESMSSITETYPEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdatedDate,
        SerialVersionId,
        SiteId,
        Status,
        TypeId,
        TypeName,
        Ou,
        CustTrxTypeId,
        CreditMemoTypeId,
        BatchSourceId,
        SiteStatusLOVVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SERIALVERSIONID = AttributesEnum.SerialVersionId.index();
    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TYPEID = AttributesEnum.TypeId.index();
    public static final int TYPENAME = AttributesEnum.TypeName.index();
    public static final int OU = AttributesEnum.Ou.index();
    public static final int CUSTTRXTYPEID = AttributesEnum.CustTrxTypeId.index();
    public static final int CREDITMEMOTYPEID = AttributesEnum.CreditMemoTypeId.index();
    public static final int BATCHSOURCEID = AttributesEnum.BatchSourceId.index();
    public static final int SITESTATUSLOVVO = AttributesEnum.SiteStatusLOVVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhceHeSmsSiteTypeEOVORowImpl() {
    }

    /**
     * Gets XxhceHeSmsSiteTypeEO entity object.
     * @return the XxhceHeSmsSiteTypeEO
     */
    public XxhceHeSmsSiteTypeEOImpl getXxhceHeSmsSiteTypeEO() {
        return (XxhceHeSmsSiteTypeEOImpl) getEntity(ENTITY_XXHCEHESMSSITETYPEEO);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @return the SERIAL_VERSION_ID
     */
    public BigDecimal getSerialVersionId() {
        return (BigDecimal) getAttributeInternal(SERIALVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @param value value to set the SERIAL_VERSION_ID
     */
    public void setSerialVersionId(BigDecimal value) {
        setAttributeInternal(SERIALVERSIONID, value);
    }

    /**
     * Gets the attribute value for SITE_ID using the alias name SiteId.
     * @return the SITE_ID
     */
    public BigDecimal getSiteId() {
        return (BigDecimal) getAttributeInternal(SITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SITE_ID using the alias name SiteId.
     * @param value value to set the SITE_ID
     */
    public void setSiteId(BigDecimal value) {
        setAttributeInternal(SITEID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TYPE_ID using the alias name TypeId.
     * @return the TYPE_ID
     */
    public BigDecimal getTypeId() {
        return (BigDecimal) getAttributeInternal(TYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE_ID using the alias name TypeId.
     * @param value value to set the TYPE_ID
     */
    public void setTypeId(BigDecimal value) {
        setAttributeInternal(TYPEID, value);
    }

    /**
     * Gets the attribute value for TYPE_NAME using the alias name TypeName.
     * @return the TYPE_NAME
     */
    public String getTypeName() {
        return (String) getAttributeInternal(TYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE_NAME using the alias name TypeName.
     * @param value value to set the TYPE_NAME
     */
    public void setTypeName(String value) {
        setAttributeInternal(TYPENAME, value);
    }

    /**
     * Gets the attribute value for OU using the alias name Ou.
     * @return the OU
     */
    public String getOu() {
        return (String) getAttributeInternal(OU);
    }

    /**
     * Sets <code>value</code> as attribute value for OU using the alias name Ou.
     * @param value value to set the OU
     */
    public void setOu(String value) {
        setAttributeInternal(OU, value);
    }

    /**
     * Gets the attribute value for CUST_TRX_TYPE_ID using the alias name CustTrxTypeId.
     * @return the CUST_TRX_TYPE_ID
     */
    public Long getCustTrxTypeId() {
        return (Long) getAttributeInternal(CUSTTRXTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_TRX_TYPE_ID using the alias name CustTrxTypeId.
     * @param value value to set the CUST_TRX_TYPE_ID
     */
    public void setCustTrxTypeId(Long value) {
        setAttributeInternal(CUSTTRXTYPEID, value);
    }

    /**
     * Gets the attribute value for CREDIT_MEMO_TYPE_ID using the alias name CreditMemoTypeId.
     * @return the CREDIT_MEMO_TYPE_ID
     */
    public Long getCreditMemoTypeId() {
        return (Long) getAttributeInternal(CREDITMEMOTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_MEMO_TYPE_ID using the alias name CreditMemoTypeId.
     * @param value value to set the CREDIT_MEMO_TYPE_ID
     */
    public void setCreditMemoTypeId(Long value) {
        setAttributeInternal(CREDITMEMOTYPEID, value);
    }

    /**
     * Gets the attribute value for BATCH_SOURCE_ID using the alias name BatchSourceId.
     * @return the BATCH_SOURCE_ID
     */
    public Long getBatchSourceId() {
        return (Long) getAttributeInternal(BATCHSOURCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCH_SOURCE_ID using the alias name BatchSourceId.
     * @param value value to set the BATCH_SOURCE_ID
     */
    public void setBatchSourceId(Long value) {
        setAttributeInternal(BATCHSOURCEID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SiteStatusLOVVO.
     */
    public RowSet getSiteStatusLOVVO() {
        return (RowSet) getAttributeInternal(SITESTATUSLOVVO);
    }
}

