package om.apps.sms.model.views;

import java.math.BigDecimal;

import java.sql.Timestamp;

import om.apps.sms.model.entities.XxhceHeSmsLinesEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 07 14:03:27 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhceHeSmsLinesEOVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXHCEHESMSLINESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Activity,
        AssetNumber,
        Attribute1,
        Attribute10,
        Attribute11,
        Attribute12,
        Attribute13,
        Attribute14,
        Attribute15,
        Attribute16,
        Attribute17,
        Attribute18,
        Attribute19,
        Attribute2,
        Attribute20,
        Attribute21,
        Attribute22,
        Attribute23,
        Attribute24,
        Attribute25,
        Attribute26,
        Attribute27,
        Attribute28,
        Attribute29,
        Attribute3,
        Attribute30,
        Attribute4,
        Attribute5,
        Attribute6,
        Attribute7,
        Attribute8,
        Attribute9,
        BatchNumber,
        CreatedBy,
        CreationDate,
        CreditCheckNotes,
        CreditCheckReleasedBy,
        CreditCheckReleasedDate,
        CreditCheckStatus,
        CreditComments,
        CreditHoldNotes,
        CreditHoldReleasedBy,
        CreditHoldReleasedDate,
        CreditHoldStatus,
        CreditReasonCode,
        CurrencyCode,
        EmployeeNumber,
        EndTime,
        ErrorMessage,
        HeaderId,
        InvoiceDate,
        InvoiceLineId,
        InvoiceNumber,
        InvOrgId,
        ItemId,
        LastUpdatedBy,
        LastUpdatedDate,
        LineId,
        ListHeaderId,
        ListLineId,
        ListPrice,
        OrderLineId,
        OrgId,
        Origin,
        PriceChangeReason,
        Quantity,
        RefInvoiceNumber,
        RequestId,
        Revision,
        SalesOrderNumber,
        SerialVersionId,        
        SmsNumber,
        SmsRequestDate,
        SoRequestDate,
        StartTime,
        SubTotal,
        TaxAmount,
        TaxRate,
        TicketLineStatus,
        TotalAmount,
        UnitPrice,
        Uom,
        VoidComments,
        WorkPerformed,
        ItemDescription,
        ItemIdTr,
        ActivityTr,
        ItemLOVVO,
        ActivityLOVVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVITY = AttributesEnum.Activity.index();
    public static final int ASSETNUMBER = AttributesEnum.AssetNumber.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int BATCHNUMBER = AttributesEnum.BatchNumber.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREDITCHECKNOTES = AttributesEnum.CreditCheckNotes.index();
    public static final int CREDITCHECKRELEASEDBY = AttributesEnum.CreditCheckReleasedBy.index();
    public static final int CREDITCHECKRELEASEDDATE = AttributesEnum.CreditCheckReleasedDate.index();
    public static final int CREDITCHECKSTATUS = AttributesEnum.CreditCheckStatus.index();
    public static final int CREDITCOMMENTS = AttributesEnum.CreditComments.index();
    public static final int CREDITHOLDNOTES = AttributesEnum.CreditHoldNotes.index();
    public static final int CREDITHOLDRELEASEDBY = AttributesEnum.CreditHoldReleasedBy.index();
    public static final int CREDITHOLDRELEASEDDATE = AttributesEnum.CreditHoldReleasedDate.index();
    public static final int CREDITHOLDSTATUS = AttributesEnum.CreditHoldStatus.index();
    public static final int CREDITREASONCODE = AttributesEnum.CreditReasonCode.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int EMPLOYEENUMBER = AttributesEnum.EmployeeNumber.index();
    public static final int ENDTIME = AttributesEnum.EndTime.index();
    public static final int ERRORMESSAGE = AttributesEnum.ErrorMessage.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int INVOICELINEID = AttributesEnum.InvoiceLineId.index();
    public static final int INVOICENUMBER = AttributesEnum.InvoiceNumber.index();
    public static final int INVORGID = AttributesEnum.InvOrgId.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int LISTHEADERID = AttributesEnum.ListHeaderId.index();
    public static final int LISTLINEID = AttributesEnum.ListLineId.index();
    public static final int LISTPRICE = AttributesEnum.ListPrice.index();
    public static final int ORDERLINEID = AttributesEnum.OrderLineId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ORIGIN = AttributesEnum.Origin.index();
    public static final int PRICECHANGEREASON = AttributesEnum.PriceChangeReason.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int REFINVOICENUMBER = AttributesEnum.RefInvoiceNumber.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int REVISION = AttributesEnum.Revision.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int SERIALVERSIONID = AttributesEnum.SerialVersionId.index();
    public static final int SMSNUMBER = AttributesEnum.SmsNumber.index();
    public static final int SMSREQUESTDATE = AttributesEnum.SmsRequestDate.index();
    public static final int SOREQUESTDATE = AttributesEnum.SoRequestDate.index();
    public static final int STARTTIME = AttributesEnum.StartTime.index();
    public static final int SUBTOTAL = AttributesEnum.SubTotal.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int TICKETLINESTATUS = AttributesEnum.TicketLineStatus.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int VOIDCOMMENTS = AttributesEnum.VoidComments.index();
    public static final int WORKPERFORMED = AttributesEnum.WorkPerformed.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int ITEMIDTR = AttributesEnum.ItemIdTr.index();
    public static final int ACTIVITYTR = AttributesEnum.ActivityTr.index();
    public static final int ITEMLOVVO = AttributesEnum.ItemLOVVO.index();
    public static final int ACTIVITYLOVVO = AttributesEnum.ActivityLOVVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhceHeSmsLinesEOVORowImpl() {
    }

    /**
     * Gets XxhceHeSmsLinesEO entity object.
     * @return the XxhceHeSmsLinesEO
     */
    public XxhceHeSmsLinesEOImpl getXxhceHeSmsLinesEO() {
        return (XxhceHeSmsLinesEOImpl) getEntity(ENTITY_XXHCEHESMSLINESEO);
    }

    /**
     * Gets the attribute value for ACTIVITY using the alias name Activity.
     * @return the ACTIVITY
     */
    public String getActivity() {
        return (String) getAttributeInternal(ACTIVITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY using the alias name Activity.
     * @param value value to set the ACTIVITY
     */
    public void setActivity(String value) {
        setAttributeInternal(ACTIVITY, value);
    }

    /**
     * Gets the attribute value for ASSET_NUMBER using the alias name AssetNumber.
     * @return the ASSET_NUMBER
     */
    public String getAssetNumber() {
        return (String) getAttributeInternal(ASSETNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSET_NUMBER using the alias name AssetNumber.
     * @param value value to set the ASSET_NUMBER
     */
    public void setAssetNumber(String value) {
        setAttributeInternal(ASSETNUMBER, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @return the ATTRIBUTE21
     */
    public BigDecimal getAttribute21() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @param value value to set the ATTRIBUTE21
     */
    public void setAttribute21(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @return the ATTRIBUTE22
     */
    public BigDecimal getAttribute22() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @param value value to set the ATTRIBUTE22
     */
    public void setAttribute22(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @return the ATTRIBUTE23
     */
    public BigDecimal getAttribute23() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @param value value to set the ATTRIBUTE23
     */
    public void setAttribute23(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @return the ATTRIBUTE24
     */
    public BigDecimal getAttribute24() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @param value value to set the ATTRIBUTE24
     */
    public void setAttribute24(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @return the ATTRIBUTE25
     */
    public BigDecimal getAttribute25() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @param value value to set the ATTRIBUTE25
     */
    public void setAttribute25(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @return the ATTRIBUTE26
     */
    public Timestamp getAttribute26() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @param value value to set the ATTRIBUTE26
     */
    public void setAttribute26(Timestamp value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @return the ATTRIBUTE27
     */
    public Timestamp getAttribute27() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @param value value to set the ATTRIBUTE27
     */
    public void setAttribute27(Timestamp value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @return the ATTRIBUTE28
     */
    public Timestamp getAttribute28() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @param value value to set the ATTRIBUTE28
     */
    public void setAttribute28(Timestamp value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @return the ATTRIBUTE29
     */
    public Timestamp getAttribute29() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @param value value to set the ATTRIBUTE29
     */
    public void setAttribute29(Timestamp value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @return the ATTRIBUTE30
     */
    public Timestamp getAttribute30() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @param value value to set the ATTRIBUTE30
     */
    public void setAttribute30(Timestamp value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for BATCH_NUMBER using the alias name BatchNumber.
     * @return the BATCH_NUMBER
     */
    public BigDecimal getBatchNumber() {
        return (BigDecimal) getAttributeInternal(BATCHNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCH_NUMBER using the alias name BatchNumber.
     * @param value value to set the BATCH_NUMBER
     */
    public void setBatchNumber(BigDecimal value) {
        setAttributeInternal(BATCHNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CREDIT_CHECK_NOTES using the alias name CreditCheckNotes.
     * @return the CREDIT_CHECK_NOTES
     */
    public String getCreditCheckNotes() {
        return (String) getAttributeInternal(CREDITCHECKNOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_CHECK_NOTES using the alias name CreditCheckNotes.
     * @param value value to set the CREDIT_CHECK_NOTES
     */
    public void setCreditCheckNotes(String value) {
        setAttributeInternal(CREDITCHECKNOTES, value);
    }

    /**
     * Gets the attribute value for CREDIT_CHECK_RELEASED_BY using the alias name CreditCheckReleasedBy.
     * @return the CREDIT_CHECK_RELEASED_BY
     */
    public BigDecimal getCreditCheckReleasedBy() {
        return (BigDecimal) getAttributeInternal(CREDITCHECKRELEASEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_CHECK_RELEASED_BY using the alias name CreditCheckReleasedBy.
     * @param value value to set the CREDIT_CHECK_RELEASED_BY
     */
    public void setCreditCheckReleasedBy(BigDecimal value) {
        setAttributeInternal(CREDITCHECKRELEASEDBY, value);
    }

    /**
     * Gets the attribute value for CREDIT_CHECK_RELEASED_DATE using the alias name CreditCheckReleasedDate.
     * @return the CREDIT_CHECK_RELEASED_DATE
     */
    public Timestamp getCreditCheckReleasedDate() {
        return (Timestamp) getAttributeInternal(CREDITCHECKRELEASEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_CHECK_RELEASED_DATE using the alias name CreditCheckReleasedDate.
     * @param value value to set the CREDIT_CHECK_RELEASED_DATE
     */
    public void setCreditCheckReleasedDate(Timestamp value) {
        setAttributeInternal(CREDITCHECKRELEASEDDATE, value);
    }

    /**
     * Gets the attribute value for CREDIT_CHECK_STATUS using the alias name CreditCheckStatus.
     * @return the CREDIT_CHECK_STATUS
     */
    public String getCreditCheckStatus() {
        return (String) getAttributeInternal(CREDITCHECKSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_CHECK_STATUS using the alias name CreditCheckStatus.
     * @param value value to set the CREDIT_CHECK_STATUS
     */
    public void setCreditCheckStatus(String value) {
        setAttributeInternal(CREDITCHECKSTATUS, value);
    }

    /**
     * Gets the attribute value for CREDIT_COMMENTS using the alias name CreditComments.
     * @return the CREDIT_COMMENTS
     */
    public String getCreditComments() {
        return (String) getAttributeInternal(CREDITCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_COMMENTS using the alias name CreditComments.
     * @param value value to set the CREDIT_COMMENTS
     */
    public void setCreditComments(String value) {
        setAttributeInternal(CREDITCOMMENTS, value);
    }

    /**
     * Gets the attribute value for CREDIT_HOLD_NOTES using the alias name CreditHoldNotes.
     * @return the CREDIT_HOLD_NOTES
     */
    public String getCreditHoldNotes() {
        return (String) getAttributeInternal(CREDITHOLDNOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_HOLD_NOTES using the alias name CreditHoldNotes.
     * @param value value to set the CREDIT_HOLD_NOTES
     */
    public void setCreditHoldNotes(String value) {
        setAttributeInternal(CREDITHOLDNOTES, value);
    }

    /**
     * Gets the attribute value for CREDIT_HOLD_RELEASED_BY using the alias name CreditHoldReleasedBy.
     * @return the CREDIT_HOLD_RELEASED_BY
     */
    public BigDecimal getCreditHoldReleasedBy() {
        return (BigDecimal) getAttributeInternal(CREDITHOLDRELEASEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_HOLD_RELEASED_BY using the alias name CreditHoldReleasedBy.
     * @param value value to set the CREDIT_HOLD_RELEASED_BY
     */
    public void setCreditHoldReleasedBy(BigDecimal value) {
        setAttributeInternal(CREDITHOLDRELEASEDBY, value);
    }

    /**
     * Gets the attribute value for CREDIT_HOLD_RELEASED_DATE using the alias name CreditHoldReleasedDate.
     * @return the CREDIT_HOLD_RELEASED_DATE
     */
    public Timestamp getCreditHoldReleasedDate() {
        return (Timestamp) getAttributeInternal(CREDITHOLDRELEASEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_HOLD_RELEASED_DATE using the alias name CreditHoldReleasedDate.
     * @param value value to set the CREDIT_HOLD_RELEASED_DATE
     */
    public void setCreditHoldReleasedDate(Timestamp value) {
        setAttributeInternal(CREDITHOLDRELEASEDDATE, value);
    }

    /**
     * Gets the attribute value for CREDIT_HOLD_STATUS using the alias name CreditHoldStatus.
     * @return the CREDIT_HOLD_STATUS
     */
    public String getCreditHoldStatus() {
        return (String) getAttributeInternal(CREDITHOLDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_HOLD_STATUS using the alias name CreditHoldStatus.
     * @param value value to set the CREDIT_HOLD_STATUS
     */
    public void setCreditHoldStatus(String value) {
        setAttributeInternal(CREDITHOLDSTATUS, value);
    }

    /**
     * Gets the attribute value for CREDIT_REASON_CODE using the alias name CreditReasonCode.
     * @return the CREDIT_REASON_CODE
     */
    public String getCreditReasonCode() {
        return (String) getAttributeInternal(CREDITREASONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_REASON_CODE using the alias name CreditReasonCode.
     * @param value value to set the CREDIT_REASON_CODE
     */
    public void setCreditReasonCode(String value) {
        setAttributeInternal(CREDITREASONCODE, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @param value value to set the CURRENCY_CODE
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber.
     * @return the EMPLOYEE_NUMBER
     */
    public String getEmployeeNumber() {
        return (String) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber.
     * @param value value to set the EMPLOYEE_NUMBER
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**
     * Gets the attribute value for END_TIME using the alias name EndTime.
     * @return the END_TIME
     */
    public Timestamp getEndTime() {
        return (Timestamp) getAttributeInternal(ENDTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for END_TIME using the alias name EndTime.
     * @param value value to set the END_TIME
     */
    public void setEndTime(Timestamp value) {
        setAttributeInternal(ENDTIME, value);
    }

    /**
     * Gets the attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @return the ERROR_MESSAGE
     */
    public String getErrorMessage() {
        return (String) getAttributeInternal(ERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @param value value to set the ERROR_MESSAGE
     */
    public void setErrorMessage(String value) {
        setAttributeInternal(ERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public BigDecimal getHeaderId() {
        return (BigDecimal) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(BigDecimal value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @return the INVOICE_DATE
     */
    public Timestamp getInvoiceDate() {
        return (Timestamp) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @param value value to set the INVOICE_DATE
     */
    public void setInvoiceDate(Timestamp value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for INVOICE_LINE_ID using the alias name InvoiceLineId.
     * @return the INVOICE_LINE_ID
     */
    public BigDecimal getInvoiceLineId() {
        return (BigDecimal) getAttributeInternal(INVOICELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_LINE_ID using the alias name InvoiceLineId.
     * @param value value to set the INVOICE_LINE_ID
     */
    public void setInvoiceLineId(BigDecimal value) {
        setAttributeInternal(INVOICELINEID, value);
    }

    /**
     * Gets the attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @return the INVOICE_NUMBER
     */
    public String getInvoiceNumber() {
        return (String) getAttributeInternal(INVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @param value value to set the INVOICE_NUMBER
     */
    public void setInvoiceNumber(String value) {
        setAttributeInternal(INVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for INV_ORG_ID using the alias name InvOrgId.
     * @return the INV_ORG_ID
     */
    public BigDecimal getInvOrgId() {
        return (BigDecimal) getAttributeInternal(INVORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for INV_ORG_ID using the alias name InvOrgId.
     * @param value value to set the INV_ORG_ID
     */
    public void setInvOrgId(BigDecimal value) {
        setAttributeInternal(INVORGID, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public BigDecimal getItemId() {
        return (BigDecimal) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(BigDecimal value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public BigDecimal getLineId() {
        return (BigDecimal) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(BigDecimal value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for LIST_HEADER_ID using the alias name ListHeaderId.
     * @return the LIST_HEADER_ID
     */
    public BigDecimal getListHeaderId() {
        return (BigDecimal) getAttributeInternal(LISTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_HEADER_ID using the alias name ListHeaderId.
     * @param value value to set the LIST_HEADER_ID
     */
    public void setListHeaderId(BigDecimal value) {
        setAttributeInternal(LISTHEADERID, value);
    }

    /**
     * Gets the attribute value for LIST_LINE_ID using the alias name ListLineId.
     * @return the LIST_LINE_ID
     */
    public BigDecimal getListLineId() {
        return (BigDecimal) getAttributeInternal(LISTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_LINE_ID using the alias name ListLineId.
     * @param value value to set the LIST_LINE_ID
     */
    public void setListLineId(BigDecimal value) {
        setAttributeInternal(LISTLINEID, value);
    }

    /**
     * Gets the attribute value for LIST_PRICE using the alias name ListPrice.
     * @return the LIST_PRICE
     */
    public BigDecimal getListPrice() {
        return (BigDecimal) getAttributeInternal(LISTPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_PRICE using the alias name ListPrice.
     * @param value value to set the LIST_PRICE
     */
    public void setListPrice(BigDecimal value) {
        setAttributeInternal(LISTPRICE, value);
    }

    /**
     * Gets the attribute value for ORDER_LINE_ID using the alias name OrderLineId.
     * @return the ORDER_LINE_ID
     */
    public BigDecimal getOrderLineId() {
        return (BigDecimal) getAttributeInternal(ORDERLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_LINE_ID using the alias name OrderLineId.
     * @param value value to set the ORDER_LINE_ID
     */
    public void setOrderLineId(BigDecimal value) {
        setAttributeInternal(ORDERLINEID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for ORIGIN using the alias name Origin.
     * @return the ORIGIN
     */
    public String getOrigin() {
        return (String) getAttributeInternal(ORIGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for ORIGIN using the alias name Origin.
     * @param value value to set the ORIGIN
     */
    public void setOrigin(String value) {
        setAttributeInternal(ORIGIN, value);
    }

    /**
     * Gets the attribute value for PRICE_CHANGE_REASON using the alias name PriceChangeReason.
     * @return the PRICE_CHANGE_REASON
     */
    public String getPriceChangeReason() {
        return (String) getAttributeInternal(PRICECHANGEREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE_CHANGE_REASON using the alias name PriceChangeReason.
     * @param value value to set the PRICE_CHANGE_REASON
     */
    public void setPriceChangeReason(String value) {
        setAttributeInternal(PRICECHANGEREASON, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for REF_INVOICE_NUMBER using the alias name RefInvoiceNumber.
     * @return the REF_INVOICE_NUMBER
     */
    public String getRefInvoiceNumber() {
        return (String) getAttributeInternal(REFINVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_INVOICE_NUMBER using the alias name RefInvoiceNumber.
     * @param value value to set the REF_INVOICE_NUMBER
     */
    public void setRefInvoiceNumber(String value) {
        setAttributeInternal(REFINVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public String getRequestId() {
        return (String) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(String value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for REVISION using the alias name Revision.
     * @return the REVISION
     */
    public BigDecimal getRevision() {
        return (BigDecimal) getAttributeInternal(REVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISION using the alias name Revision.
     * @param value value to set the REVISION
     */
    public void setRevision(BigDecimal value) {
        setAttributeInternal(REVISION, value);
    }

    /**
     * Gets the attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @return the SALES_ORDER_NUMBER
     */
    public String getSalesOrderNumber() {
        return (String) getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @param value value to set the SALES_ORDER_NUMBER
     */
    public void setSalesOrderNumber(String value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }
    /**
     * Gets the attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @return the SERIAL_VERSION_ID
     */
    public BigDecimal getSerialVersionId() {
        return (BigDecimal) getAttributeInternal(SERIALVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @param value value to set the SERIAL_VERSION_ID
     */
    public void setSerialVersionId(BigDecimal value) {
        setAttributeInternal(SERIALVERSIONID, value);
    }


    /**
     * Gets the attribute value for SMS_NUMBER using the alias name SmsNumber.
     * @return the SMS_NUMBER
     */
    public Number getSmsNumber() {
        return (Number) getAttributeInternal(SMSNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SMS_NUMBER using the alias name SmsNumber.
     * @param value value to set the SMS_NUMBER
     */
    public void setSmsNumber(Number value) {
        setAttributeInternal(SMSNUMBER, value);
    }

    /**
     * Gets the attribute value for SMS_REQUEST_DATE using the alias name SmsRequestDate.
     * @return the SMS_REQUEST_DATE
     */
    public Timestamp getSmsRequestDate() {
        return (Timestamp) getAttributeInternal(SMSREQUESTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SMS_REQUEST_DATE using the alias name SmsRequestDate.
     * @param value value to set the SMS_REQUEST_DATE
     */
    public void setSmsRequestDate(Timestamp value) {
        setAttributeInternal(SMSREQUESTDATE, value);
    }

    /**
     * Gets the attribute value for SO_REQUEST_DATE using the alias name SoRequestDate.
     * @return the SO_REQUEST_DATE
     */
    public Timestamp getSoRequestDate() {
        return (Timestamp) getAttributeInternal(SOREQUESTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SO_REQUEST_DATE using the alias name SoRequestDate.
     * @param value value to set the SO_REQUEST_DATE
     */
    public void setSoRequestDate(Timestamp value) {
        setAttributeInternal(SOREQUESTDATE, value);
    }

    /**
     * Gets the attribute value for START_TIME using the alias name StartTime.
     * @return the START_TIME
     */
    public Timestamp getStartTime() {
        return (Timestamp) getAttributeInternal(STARTTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for START_TIME using the alias name StartTime.
     * @param value value to set the START_TIME
     */
    public void setStartTime(Timestamp value) {
        setAttributeInternal(STARTTIME, value);
    }

    /**
     * Gets the attribute value for SUB_TOTAL using the alias name SubTotal.
     * @return the SUB_TOTAL
     */
    public BigDecimal getSubTotal() {
        if (getQuantity() != null && getUnitPrice() != null) {
            BigDecimal subtotal = getQuantity().multiply(getUnitPrice());
            return subtotal;
        }
        return (BigDecimal) getAttributeInternal(SUBTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_TOTAL using the alias name SubTotal.
     * @param value value to set the SUB_TOTAL
     */
    public void setSubTotal(BigDecimal value) {
        setAttributeInternal(SUBTOTAL, value);
    }

    /**
     * Gets the attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @return the TAX_AMOUNT
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @param value value to set the TAX_AMOUNT
     */
    public void setTaxAmount(BigDecimal value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for TAX_RATE using the alias name TaxRate.
     * @return the TAX_RATE
     */
    public BigDecimal getTaxRate() {
        return (BigDecimal) getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE using the alias name TaxRate.
     * @param value value to set the TAX_RATE
     */
    public void setTaxRate(BigDecimal value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for TICKET_LINE_STATUS using the alias name TicketLineStatus.
     * @return the TICKET_LINE_STATUS
     */
    public String getTicketLineStatus() {
        return (String) getAttributeInternal(TICKETLINESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for TICKET_LINE_STATUS using the alias name TicketLineStatus.
     * @param value value to set the TICKET_LINE_STATUS
     */
    public void setTicketLineStatus(String value) {
        setAttributeInternal(TICKETLINESTATUS, value);
    }

    /**
     * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @return the TOTAL_AMOUNT
     */
    public BigDecimal getTotalAmount() {
        if (getSubTotal() != null && getTaxAmount() != null) {
            BigDecimal total = getSubTotal().add(getTaxAmount());
            return total;
        }
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @param value value to set the TOTAL_AMOUNT
     */
    public void setTotalAmount(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @return the UNIT_PRICE
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @param value value to set the UNIT_PRICE
     */
    public void setUnitPrice(BigDecimal value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for VOID_COMMENTS using the alias name VoidComments.
     * @return the VOID_COMMENTS
     */
    public String getVoidComments() {
        return (String) getAttributeInternal(VOIDCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for VOID_COMMENTS using the alias name VoidComments.
     * @param value value to set the VOID_COMMENTS
     */
    public void setVoidComments(String value) {
        setAttributeInternal(VOIDCOMMENTS, value);
    }

    /**
     * Gets the attribute value for WORK_PERFORMED using the alias name WorkPerformed.
     * @return the WORK_PERFORMED
     */
    public String getWorkPerformed() {
        return (String) getAttributeInternal(WORKPERFORMED);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_PERFORMED using the alias name WorkPerformed.
     * @param value value to set the WORK_PERFORMED
     */
    public void setWorkPerformed(String value) {
        setAttributeInternal(WORKPERFORMED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String) getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemDescription.
     * @param value value to set the  ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemIdTr.
     * @return the ItemIdTr
     */
    public String getItemIdTr() {
        return (String) getAttributeInternal(ITEMIDTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemIdTr.
     * @param value value to set the  ItemIdTr
     */
    public void setItemIdTr(String value) {
        setAttributeInternal(ITEMIDTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActivityTr.
     * @return the ActivityTr
     */
    public String getActivityTr() {
        return (String) getAttributeInternal(ACTIVITYTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActivityTr.
     * @param value value to set the  ActivityTr
     */
    public void setActivityTr(String value) {
        setAttributeInternal(ACTIVITYTR, value);
    }


      /**
     * Gets the view accessor <code>RowSet</code> ItemLOVVO.
     */
    public RowSet getItemLOVVO() {
        return (RowSet) getAttributeInternal(ITEMLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ActivityLOVVO.
     */
    public RowSet getActivityLOVVO() {
        return (RowSet) getAttributeInternal(ACTIVITYLOVVO);
    }
}

