package om.apps.sms.model.views;

import java.math.BigDecimal;

import java.sql.Timestamp;

import om.apps.sms.model.entities.XxhceHeSmsHeadersEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 07 14:02:27 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhceHeSmsHeadersEOVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXHCEHESMSHEADERSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Attribute1,
        Attribute10,
        Attribute11,
        Attribute12,
        Attribute13,
        Attribute14,
        Attribute15,
        Attribute16,
        Attribute17,
        Attribute18,
        Attribute19,
        Attribute2,
        Attribute20,
        Attribute21,
        Attribute22,
        Attribute23,
        Attribute24,
        Attribute25,
        Attribute26,
        Attribute27,
        Attribute28,
        Attribute29,
        Attribute3,
        Attribute30,
        Attribute4,
        Attribute5,
        Attribute6,
        Attribute7,
        Attribute8,
        Attribute9,
        CreatedBy,
        CreationDate,
        CustomerAccountNumber,
        HeaderId,
        LastUpdatedBy,
        LastUpdatedDate,
        ListHeaderId,
        PoNumber,
        SiteId,
        Type,
        OrgId,
        SiteDescription,
        CustomerShipToDesc,
        CustomerBillToDesc,
        PriceList,
        InvOrgId,
        ShipToSiteUseId,
        BillToSiteUseId,
        SerialVersionId,
        XxhceHeSmsLinesEOVO,
        SiteLOVVO,
        TypeLOVVO,
        CustShipToLOVVO,
        CustBillToLOVVO,
        PriceListLOVVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUSTOMERACCOUNTNUMBER = AttributesEnum.CustomerAccountNumber.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LISTHEADERID = AttributesEnum.ListHeaderId.index();
    public static final int PONUMBER = AttributesEnum.PoNumber.index();
    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int SITEDESCRIPTION = AttributesEnum.SiteDescription.index();
    public static final int CUSTOMERSHIPTODESC = AttributesEnum.CustomerShipToDesc.index();
    public static final int CUSTOMERBILLTODESC = AttributesEnum.CustomerBillToDesc.index();
    public static final int PRICELIST = AttributesEnum.PriceList.index();
    public static final int INVORGID = AttributesEnum.InvOrgId.index();
    public static final int SHIPTOSITEUSEID = AttributesEnum.ShipToSiteUseId.index();
    public static final int BILLTOSITEUSEID = AttributesEnum.BillToSiteUseId.index();
    public static final int SERIALVERSIONID = AttributesEnum.SerialVersionId.index();
    public static final int XXHCEHESMSLINESEOVO = AttributesEnum.XxhceHeSmsLinesEOVO.index();
    public static final int SITELOVVO = AttributesEnum.SiteLOVVO.index();
    public static final int TYPELOVVO = AttributesEnum.TypeLOVVO.index();
    public static final int CUSTSHIPTOLOVVO = AttributesEnum.CustShipToLOVVO.index();
    public static final int CUSTBILLTOLOVVO = AttributesEnum.CustBillToLOVVO.index();
    public static final int PRICELISTLOVVO = AttributesEnum.PriceListLOVVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhceHeSmsHeadersEOVORowImpl() {
    }

    /**
     * Gets XxhceHeSmsHeadersEO entity object.
     * @return the XxhceHeSmsHeadersEO
     */
    public XxhceHeSmsHeadersEOImpl getXxhceHeSmsHeadersEO() {
        return (XxhceHeSmsHeadersEOImpl) getEntity(ENTITY_XXHCEHESMSHEADERSEO);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @return the ATTRIBUTE21
     */
    public BigDecimal getAttribute21() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @param value value to set the ATTRIBUTE21
     */
    public void setAttribute21(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @return the ATTRIBUTE22
     */
    public BigDecimal getAttribute22() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @param value value to set the ATTRIBUTE22
     */
    public void setAttribute22(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @return the ATTRIBUTE23
     */
    public BigDecimal getAttribute23() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @param value value to set the ATTRIBUTE23
     */
    public void setAttribute23(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @return the ATTRIBUTE24
     */
    public BigDecimal getAttribute24() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @param value value to set the ATTRIBUTE24
     */
    public void setAttribute24(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @return the ATTRIBUTE25
     */
    public BigDecimal getAttribute25() {
        return (BigDecimal) getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @param value value to set the ATTRIBUTE25
     */
    public void setAttribute25(BigDecimal value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @return the ATTRIBUTE26
     */
    public Timestamp getAttribute26() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @param value value to set the ATTRIBUTE26
     */
    public void setAttribute26(Timestamp value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @return the ATTRIBUTE27
     */
    public Timestamp getAttribute27() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @param value value to set the ATTRIBUTE27
     */
    public void setAttribute27(Timestamp value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @return the ATTRIBUTE28
     */
    public Timestamp getAttribute28() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @param value value to set the ATTRIBUTE28
     */
    public void setAttribute28(Timestamp value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @return the ATTRIBUTE29
     */
    public Timestamp getAttribute29() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @param value value to set the ATTRIBUTE29
     */
    public void setAttribute29(Timestamp value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @return the ATTRIBUTE30
     */
    public Timestamp getAttribute30() {
        return (Timestamp) getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @param value value to set the ATTRIBUTE30
     */
    public void setAttribute30(Timestamp value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CUSTOMER_ACCOUNT_NUMBER using the alias name CustomerAccountNumber.
     * @return the CUSTOMER_ACCOUNT_NUMBER
     */
    public BigDecimal getCustomerAccountNumber() {
        return (BigDecimal) getAttributeInternal(CUSTOMERACCOUNTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ACCOUNT_NUMBER using the alias name CustomerAccountNumber.
     * @param value value to set the CUSTOMER_ACCOUNT_NUMBER
     */
    public void setCustomerAccountNumber(BigDecimal value) {
        setAttributeInternal(CUSTOMERACCOUNTNUMBER, value);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public BigDecimal getHeaderId() {
        return (BigDecimal) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(BigDecimal value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for LIST_HEADER_ID using the alias name ListHeaderId.
     * @return the LIST_HEADER_ID
     */
    public BigDecimal getListHeaderId() {
        return (BigDecimal) getAttributeInternal(LISTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_HEADER_ID using the alias name ListHeaderId.
     * @param value value to set the LIST_HEADER_ID
     */
    public void setListHeaderId(BigDecimal value) {
        setAttributeInternal(LISTHEADERID, value);
    }


    /**
     * Gets the attribute value for PO_NUMBER using the alias name PoNumber.
     * @return the PO_NUMBER
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_NUMBER using the alias name PoNumber.
     * @param value value to set the PO_NUMBER
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**
     * Gets the attribute value for SITE_ID using the alias name SiteId.
     * @return the SITE_ID
     */
    public BigDecimal getSiteId() {
        return (BigDecimal) getAttributeInternal(SITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SITE_ID using the alias name SiteId.
     * @param value value to set the SITE_ID
     */
    public void setSiteId(BigDecimal value) {
        setAttributeInternal(SITEID, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SiteDescription.
     * @return the SiteDescription
     */
    public String getSiteDescription() {
        return (String) getAttributeInternal(SITEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SiteDescription.
     * @param value value to set the  SiteDescription
     */
    public void setSiteDescription(String value) {
        setAttributeInternal(SITEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerShipToDesc.
     * @return the CustomerShipToDesc
     */
    public String getCustomerShipToDesc() {
        return (String) getAttributeInternal(CUSTOMERSHIPTODESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerShipToDesc.
     * @param value value to set the  CustomerShipToDesc
     */
    public void setCustomerShipToDesc(String value) {
        setAttributeInternal(CUSTOMERSHIPTODESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerBillToDesc.
     * @return the CustomerBillToDesc
     */
    public String getCustomerBillToDesc() {
        if(this.getCustBillToLOVVO().getEstimatedRowCount()==1){
            Row row=this.getCustBillToLOVVO().first();
            String BillTo=(String)row.getAttribute("CustomerShipTo");
            BigDecimal site=(BigDecimal)row.getAttribute("SiteUseId");
            this.setBillToSiteUseId(site);
            return BillTo;
        }
        return (String) getAttributeInternal(CUSTOMERBILLTODESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerBillToDesc.
     * @param value value to set the  CustomerBillToDesc
     */
    public void setCustomerBillToDesc(String value) {
        setAttributeInternal(CUSTOMERBILLTODESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PriceList.
     * @return the PriceList
     */
    public String getPriceList() {
        if(this.getPriceListLOVVO().getEstimatedRowCount()==1){
            Row row=this.getPriceListLOVVO().first();
            String priceListTo=(String)row.getAttribute("Name");
            BigDecimal listHdrId=(BigDecimal)row.getAttribute("ListHeaderId");
            this.setShipToSiteUseId(listHdrId);
            return priceListTo;
        }
        return (String) getAttributeInternal(PRICELIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PriceList.
     * @param value value to set the  PriceList
     */
    public void setPriceList(String value) {
        setAttributeInternal(PRICELIST, value);
    }

    /**
     * Gets the attribute value for INV_ORG_ID using the alias name InvOrgId.
     * @return the INV_ORG_ID
     */
    public BigDecimal getInvOrgId() {
        return (BigDecimal) getAttributeInternal(INVORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for INV_ORG_ID using the alias name InvOrgId.
     * @param value value to set the INV_ORG_ID
     */
    public void setInvOrgId(BigDecimal value) {
        setAttributeInternal(INVORGID, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_SITE_USE_ID using the alias name ShipToSiteUseId.
     * @return the SHIP_TO_SITE_USE_ID
     */
    public BigDecimal getShipToSiteUseId() {
        return (BigDecimal) getAttributeInternal(SHIPTOSITEUSEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_SITE_USE_ID using the alias name ShipToSiteUseId.
     * @param value value to set the SHIP_TO_SITE_USE_ID
     */
    public void setShipToSiteUseId(BigDecimal value) {
        setAttributeInternal(SHIPTOSITEUSEID, value);
    }

    /**
     * Gets the attribute value for BILL_TO_SITE_USE_ID using the alias name BillToSiteUseId.
     * @return the BILL_TO_SITE_USE_ID
     */
    public BigDecimal getBillToSiteUseId() {
        return (BigDecimal) getAttributeInternal(BILLTOSITEUSEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_TO_SITE_USE_ID using the alias name BillToSiteUseId.
     * @param value value to set the BILL_TO_SITE_USE_ID
     */
    public void setBillToSiteUseId(BigDecimal value) {
        setAttributeInternal(BILLTOSITEUSEID, value);
    }

    /**
     * Gets the attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @return the SERIAL_VERSION_ID
     */
    public BigDecimal getSerialVersionId() {
        return (BigDecimal) getAttributeInternal(SERIALVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @param value value to set the SERIAL_VERSION_ID
     */
    public void setSerialVersionId(BigDecimal value) {
        setAttributeInternal(SERIALVERSIONID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxhceHeSmsLinesEOVO.
     */
    public RowIterator getXxhceHeSmsLinesEOVO() {
        return (RowIterator) getAttributeInternal(XXHCEHESMSLINESEOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SiteLOVVO.
     */
    public RowSet getSiteLOVVO() {
        return (RowSet) getAttributeInternal(SITELOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TypeLOVVO.
     */
    public RowSet getTypeLOVVO() {
        return (RowSet) getAttributeInternal(TYPELOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustShipToLOVVO.
     */
    public RowSet getCustShipToLOVVO() {
        return (RowSet) getAttributeInternal(CUSTSHIPTOLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustBillToLOVVO.
     */
    public RowSet getCustBillToLOVVO() {
        return (RowSet) getAttributeInternal(CUSTBILLTOLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PriceListLOVVO.
     */
    public RowSet getPriceListLOVVO() {
        return (RowSet) getAttributeInternal(PRICELISTLOVVO);
    }
}

