package om.apps.sms.model.views;

import java.math.BigDecimal;

import java.sql.Timestamp;

import om.apps.sms.model.entities.XxhceHeSmsSiteMtncEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 24 14:29:29 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhceHeSmsSiteMtncEOVORowImpl extends ViewRowImpl {

    public static final int ENTITY_XXHCEHESMSSITEMTNCEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CreatedBy,
        CreationDate,
        Id,
        LastUpdatedBy,
        LastUpdatedDate,
        OrganizationCode,
        OrganizationId,
        SiteId,
        Status,
        SerialVersionId,
        SiteDesc,
        XxhceHeSmsSiteTypeEOVO,
        SiteSetupLOVVO,
        SiteStatusLOVVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ORGANIZATIONCODE = AttributesEnum.OrganizationCode.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();
    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SERIALVERSIONID = AttributesEnum.SerialVersionId.index();
    public static final int SITEDESC = AttributesEnum.SiteDesc.index();
    public static final int XXHCEHESMSSITETYPEEOVO = AttributesEnum.XxhceHeSmsSiteTypeEOVO.index();
    public static final int SITESETUPLOVVO = AttributesEnum.SiteSetupLOVVO.index();
    public static final int SITESTATUSLOVVO = AttributesEnum.SiteStatusLOVVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhceHeSmsSiteMtncEOVORowImpl() {
    }

    /**
     * Gets XxhceHeSmsSiteMtncEO entity object.
     * @return the XxhceHeSmsSiteMtncEO
     */
    public XxhceHeSmsSiteMtncEOImpl getXxhceHeSmsSiteMtncEO() {
        return (XxhceHeSmsSiteMtncEOImpl) getEntity(ENTITY_XXHCEHESMSSITEMTNCEO);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for ORGANIZATION_CODE using the alias name OrganizationCode.
     * @return the ORGANIZATION_CODE
     */
    public String getOrganizationCode() {
        return (String) getAttributeInternal(ORGANIZATIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORGANIZATION_CODE using the alias name OrganizationCode.
     * @param value value to set the ORGANIZATION_CODE
     */
    public void setOrganizationCode(String value) {
        setAttributeInternal(ORGANIZATIONCODE, value);
    }

    /**
     * Gets the attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @return the ORGANIZATION_ID
     */
    public BigDecimal getOrganizationId() {
        return (BigDecimal) getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @param value value to set the ORGANIZATION_ID
     */
    public void setOrganizationId(BigDecimal value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * Gets the attribute value for SITE_ID using the alias name SiteId.
     * @return the SITE_ID
     */
    public Number getSiteId() {
        return (Number) getAttributeInternal(SITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SITE_ID using the alias name SiteId.
     * @param value value to set the SITE_ID
     */
    public void setSiteId(Number value) {
        setAttributeInternal(SITEID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @return the SERIAL_VERSION_ID
     */
    public BigDecimal getSerialVersionId() {
        return (BigDecimal) getAttributeInternal(SERIALVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIAL_VERSION_ID using the alias name SerialVersionId.
     * @param value value to set the SERIAL_VERSION_ID
     */
    public void setSerialVersionId(BigDecimal value) {
        setAttributeInternal(SERIALVERSIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SiteDesc.
     * @return the SiteDesc
     */
    public String getSiteDesc() {
        return (String) getAttributeInternal(SITEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SiteDesc.
     * @param value value to set the  SiteDesc
     */
    public void setSiteDesc(String value) {
        setAttributeInternal(SITEDESC, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxhceHeSmsSiteTypeEOVO.
     */
    public RowIterator getXxhceHeSmsSiteTypeEOVO() {
        return (RowIterator) getAttributeInternal(XXHCEHESMSSITETYPEEOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SiteSetupLOVVO.
     */
    public RowSet getSiteSetupLOVVO() {
        return (RowSet) getAttributeInternal(SITESETUPLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SiteStatusLOVVO.
     */
    public RowSet getSiteStatusLOVVO() {
        return (RowSet) getAttributeInternal(SITESTATUSLOVVO);
    }
}

